name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: kamiazya/setup-graphviz@v1
      - run: yarn
      - run: yarn test
      - run: yarn build
        env:
          GOOGLE_TRACKING_ID: ${{ secrets.GOOGLE_TRACKING_ID }}
          GOOGLE_ADSENSE_ID: ${{ secrets.GOOGLE_ADSENSE_ID }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: tanmen.work
